# Generated by Django 5.1.3 on 2025-12-22 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Achievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="achievements/")),
            ],
        ),
        migrations.CreateModel(
            name="Certification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("institute", models.CharField(max_length=150)),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("university", models.CharField(max_length=150)),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.CharField(max_length=100)),
                ("title", models.CharField(max_length=150)),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("canvas_image", models.ImageField(upload_to="projects/canvas/")),
                (
                    "svg_file",
                    models.FileField(blank=True, null=True, upload_to="projects/svg/"),
                ),
                ("tag", models.CharField(max_length=100)),
                ("title", models.CharField(max_length=200)),
                ("body", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("website", "Website"),
                            ("mobile", "Mobile"),
                            ("live", "Live"),
                            ("case_study", "Case Study"),
                            ("graphics", "Graphics"),
                            ("saas", "SaaS"),
                            ("dashboard", "Dashboard"),
                            ("landing_page", "Landing Page"),
                        ],
                        max_length=20,
                    ),
                ),
                ("duration", models.CharField(max_length=50)),
                ("overview_video_link", models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="MyProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("resume", models.FileField(upload_to="resumes/")),
                ("website_design_count", models.PositiveIntegerField(default=0)),
                ("mobile_app_design_count", models.PositiveIntegerField(default=0)),
                ("live_project_count", models.PositiveIntegerField(default=0)),
                ("about_me", models.TextField()),
                ("why_hire_me", models.TextField()),
                (
                    "expertise",
                    models.CharField(help_text="Comma separated", max_length=255),
                ),
                (
                    "skills",
                    models.CharField(help_text="Comma separated", max_length=255),
                ),
                (
                    "profile_image",
                    models.FileField(help_text="SVG preferred", upload_to="profile/"),
                ),
                ("vision", models.ImageField(upload_to="vision/")),
                (
                    "achievement_images_gallery",
                    models.ManyToManyField(blank=True, to="app.achievement"),
                ),
            ],
        ),
    ]
