# Generated by Django 5.1.3 on 2026-01-10 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="is_favorite",
            field=models.BooleanField(default=False),
        ),
    ]
